### ISSUE TITLE
build.gradle in a maven project?

### ISSUE THREAD

**Issue by MarinCervinschi** [nbicocchi/learn-java-javafx#3]
our today's task:

Create a new JavaFX Project
In IntelliJ go to File | New | Project... and choose JavaFX. Specify the Name of the project (e.g. AddressApp), select Java, and MAVEN.

following..

For our simple data model it's much easier to use JSON. We'll use a library called [Jackson]. To use Jackson, add the following three lines to the dependencies section of your BUILD.GRADLE

It is an issue or I do not understand how to do it?

**Comment by nbicocchi** [comment]
Fixed! Thanks
